# Generated by Django 3.2.12 on 2023-03-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Phone',
            new_name='PhoneNumber',
        ),
    ]
