# Generated by Django 3.2.12 on 2023-03-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230314_0507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='index',
        ),
    ]
