# Generated by Django 3.2.12 on 2023-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_customer_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=54)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
    ]
