# Generated by Django 3.2.12 on 2023-03-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index',
        ),
    ]
