# Generated by Django 4.1.7 on 2023-03-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
    ]
